### ISSUE TITLE
[FIR] Option numbers 1, 2 not working after IVR Recording end

### ISSUE THREAD

**Issue by vinaytaragi** [hackergram/shwaas-extended#3]
When She says "Sandesh record karne ke liye 1 dabayen" and I press 1 after the line finished, not working. I have to press 1 during the recording play.

**Comment by arjunvenkatraman** [comment]
This issue is related to DTMF settings on the GSM gateway (Matrix SETU ATA 211G in this case)
I have changed it from "out-band" to "in-band" - anecdotal evidence says that it has made a difference, need to have a quantitative analysis of the logs to appropriately track

**Comment by arjunvenkatraman** [comment]
Fixed
