### ISSUE TITLE
[QUESTION] Unable to find sample.py file

### ISSUE THREAD

**Issue by ikalorano** [hackergram/shwaas-extended#7]
I am unable to find sample.py file in /opt/mojobol/bin folder
![image](https://user-images.githubusercontent.com/47449474/125156643-25244a00-e184-11eb-952d-843f4835b534.png)

**Comment by arjunvenkatraman** [comment]
You can use mojobol-svr.py in place of sample.py as a workaround

**Comment by arjunvenkatraman** [comment]
TODO - Convert mojobol-svr.py to sample.py and add explanatory comments


@ikalorano you can try to read through the code in mojobol-svr.py and take a stab at the comments - if it doesn't work out, will revisit next weekend

**Comment by arjunvenkatraman** [comment]
https://gitlab.com/mojolab/mojobol/-/blob/master/bin/mojobol-svr.py is the base file you can use
