### ISSUE TITLE
[QUESTION] Do I have to create voh.conf from sampleserver.conf ? 

### ISSUE THREAD

**Issue by ikalorano** [hackergram/shwaas-extended#9]
I have put the path to sample.py in extensions.conf
![image](https://user-images.githubusercontent.com/47449474/130795416-56cc141e-15dd-4a4b-a23c-7d9786e08f7c.png)
I have created /opt/voh folder and copied all the call workflows there
I have create /opt/voiceofhimalaya folder which is empty right now
The following image is from sampleserver.conf
![image](https://user-images.githubusercontent.com/47449474/130795712-4a602771-8ba3-4435-a0c5-a543b0af3e9f.png)
The following image is from sip.conf
![image](https://user-images.githubusercontent.com/47449474/130795997-a3ce66b2-0ece-4885-be6f-7ab50d31aaca.png)

**Comment by arjunvenkatraman** [comment]
If you copied your ```sample.py``` from this file - https://gitlab.com/mojolab/mojobol/-/blob/master/bin/mojobol-svr.py
then on line 10 you will see the path to the config file - you can either change the sample.py to point to your file or change your file name to the one referred in sample.py
